name: build GPU

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: compile
      run: |
        cd GPUtemp
        mkdir build
        gcc -o build/gpu gpu.c
        cd ..
    
    - name: compress
      run: tar -cvf ./GPUtemp/artifacts.tar ./GPUtemp/build
      
    - name: upload macOS binary
      uses: actions/upload-artifact@v2
      with:
        name: assets
        path: GPUtemp/build
