name: build CPU

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: compile
      run: |
        cd CPUtemp
        mkdir build
        gcc -o build/cpu cpu.c
        cd ..
    
    - name: compress
      run: tar -cvf ./CPUtemp/artifacts.tar ./CPUtemp/build
    
    - name: upload macOS binary
      uses: actions/upload-artifact@v2
      with:
        name: assets
        path: CPUtemp/build
